user: email@librato.de
token: sometoken

slack:
    webhook: 'https://hooks.slack.com/services/TXXXXXX/XXXXXX/xxxxxxx'
    channel: '#general'
    botname: 'CO2bot'
    icon: ':monkey_face:'
    upper_threshold: 1000
    lower_threshold: 600
